### ISSUE TITLE
Readonly select

### ISSUE THREAD

**Issue by felinuxltda** [nobleclem/jQuery-MultiSelect#111]
Is there a way to preserve the select 'readonly' attribute and show the combobox in readonly state too?

**Comment by nobleclem** [comment]
So select readonly is deprecated and doesn't work at least in Chrome.  So I am not sure its something I want to support in this plugin.  However its not saying you can't add the functionality using the `onOptionClick` callback.  Since that callback is executed after the state change of the option but before the placeholder text is updated you should be able to simply just undo the state change.
