### ISSUE TITLE
Not displaying the Disabled Default selected value

### ISSUE THREAD

**Issue by hari567** [nobleclem/jQuery-MultiSelect#115]
Hi,
Thank you for providing us with an effective solution to the Multiselect checkbox issue.

My query here is- I have a default selection to be displayed for the first time when the control is loaded and it should be non editable(the default selected checkboxes should be disabled).
when i pass the attributes{disabled:true} for the default selected values, the values are not displayed in the control by default.
And when i try this, $('select[multiple]').val(), it is giving me empty value.

can you please suggest a solution for this.

Thanks
Hari

**Comment by nobleclem** [comment]
Can you try something for me.  Can you go to line 561 and uncomment it and see if it works?

From:
```
// add custom user attributes
if( thisGOption.hasOwnProperty('attributes') && Object.keys( thisGOption.attributes ).length ) {
    //selOption.attr( thisGOption.attributes );
}
```

To:
```
// add custom user attributes
if( thisGOption.hasOwnProperty('attributes') && Object.keys( thisGOption.attributes ).length ) {
    selOption.attr( thisGOption.attributes );
}
```

**Comment by hari567** [comment]
Hi, Thanks for replying.

i have uncommented the code and tried to see if it works. But the default selected value with disabled attribute property is still not visible in the button. No new span element is created for this value.

**Comment by nobleclem** [comment]
Did some more digging and realized what the issue was.  So by the nature of javascript disabled items are not included in the .val() (jQuery function) result.  So I wrote a check to look for selected disabled items in the select list and uses an alternate (less efficient) method of getting selected values.

This will not resolve your `$('select[multiple]').val()` usage.  If you want disabled use the disabled attribute and still include it in your selected value list you will want to do something like:
```
var thisVals = $('select[multiple] option:selected').map(function(){
    return $(this).val();
});
```

**Comment by hari567** [comment]
Thanks.
I tried the same solution for displaying the disabled values in the button also.
It worked.
