### ISSUE TITLE
Best way to load huge list of option without slow or laggy

### ISSUE THREAD

**Issue by anil3a** [nobleclem/jQuery-MultiSelect#124]
I am trying to load a huge list of options approx. 8000 options, and it very slow. It slowing my whole page, slowing other jquery to run, slowing itself when clicked, takes time to dropdown. I agree it could be slow when clicking dropdown, but the whole page is slow when scrolling, clicking popup.

These options are not dynamic, they are select dropdown already loaded and i have implemented your jquery-multiselect as follow:
```
 $('#filterBrandDropDown').multiselect({
            columns: 1,
            placeholder: 'None excluded',
            onLoad: function(){
                $("#filterBrandDropDown").closest('.CustomMultipleDrop').show();
            },
            search: true
        });
```

**Comment by nobleclem** [comment]
So larger lists like this have always been troubling for this plugin.  Some of it has to do with certain sections of code that are triggering reflows/redraws in order to get information it needs.

However I have done some more profiling and optimization of the code to assist in this.  Give 2.4.10 a try and see if it helps.  Most of what I looked at was time spent during the initial load.  It's possible just due to the large number of elements that have to be created and other actions on your site the redraws are just too much for both.

If I get more time I will try and continue for more optimization but there will be a limit of whats possible while maintaining features.
