### ISSUE TITLE
Opening Multi-Select Control

### ISSUE THREAD

**Issue by BlackBeanChicken** [nobleclem/jQuery-MultiSelect#125]
Is there a way to open a Multi-Select control when it first loads or by triggering it to open from JavaScript?

Thanks for any help :)

**Comment by nobleclem** [comment]
You could try this:
```
$('select[multiple]').multiselect({
    onLoad: function( element ){
        $(element).next('.ms-options-wrap').addClass('ms-active');
    }
});
```

**Comment by BlackBeanChicken** [comment]
Perfect!! works well. Exactly what I needed.
I needed to keep the control open on a reload of the partial page after a checkbox was clicked.
Hopefully a simple AutoOpen or OpenOnLoad could be added to the library on the future.

**Comment by nobleclem** [comment]
Glad it worked.

I probably won't add that as a base feature.  I don't want to riddle the plugin with a bunch of low use cases that could simply be done within a callback.  I think some plugins become over built instead of something with the basics that could be tailored to someones unique requirements.
