### ISSUE TITLE
Loading with RequireJS

### ISSUE THREAD

**Issue by andrei572** [nobleclem/jQuery-MultiSelect#126]
Great plugin! However, when I try using it on page that (for reasons beyond my control) has to use RequireJS for module loading, I get some errors. 

What is the correct way of loading the plugin with RequireJS?

**Comment by nobleclem** [comment]
Never used RequireJS.  What errors are you getting?

**Comment by andrei572** [comment]
jquery-1.11.1.min.js?t=636532057928973715:2 Uncaught Error: Syntax error, unrecognized expression: option[value="function (a){if(a<0||a>this.length){throw"Index out of bounds."}this.splice(a,1)}"]
    at Function.fb.error (jquery-1.11.1.min.js?t=636532057928973715:2)
    at fb.tokenize (jquery-1.11.1.min.js?t=636532057928973715:2)
    at Function.fb [as find] (jquery-1.11.1.min.js?t=636532057928973715:2)
    at m.fn.init.find (jquery-1.11.1.min.js?t=636532057928973715:2)
    at MultiSelect._updatePlaceholderText (jquery.multiselect.js?t=636532057928973715:809)
    at MultiSelect.loadOptions (jquery.multiselect.js?t=636532057928973715:648)
    at MultiSelect.load (jquery.multiselect.js?t=636532057928973715:448)
    at new MultiSelect (jquery.multiselect.js?t=636532057928973715:128)
    at HTMLSelectElement.<anonymous> (jquery.multiselect.js?t=636532057928973715:897)
    at Function.each (jquery-1.11.1.min.js?t=636532057928973715:2)

I get the same error with different versions of JQuery

**Comment by nobleclem** [comment]
So some of this is speculation because of my limited knowledge of RequireJS...

I suspect that since this plugin is not AMD spec compatible and the way you are attempted to include this plugin with RequireJS that its simply barfing our an error that makes no sense.

Doing some looking there seems to be a way with RequireJS to load non AMD compatible plugins.  Sounds like the key is the "[shim config](http://requirejs.org/docs/api.html#config-shim)".  There is some talk about it in this articles "[approach 1](https://www.caffeinecoding.com/jquery-and-amd/)" as well.

Hopefully as a RequireJS user this will make more sense than it does for me.  Other than this without going through the motions of trying to get a working environment example setup with RequireJS there probably is not much more I can do.

**Comment by andrei572** [comment]
Thanks for the response. I did try a shim in the RequireJS config:

       shim: {
      "jquery.multiselect": {deps:["jquery"]}
    }

Are there dependencies other than JQuery?

**Comment by nobleclem** [comment]
Nope.  It's built to not be dependent on anything but jQuery.

Is it possible some minification of the plugin is happening?  The part of the error you pasted `option[value="function (a){if(a<0||a>this.length){throw"Index out of bounds."}this.splice(a,1)}"]` is only found in two spots in this plugin.  Line 460 and 809.  Line 809 based on the rest of the error stack provided could be the most likely point as _updatePlaceholderText is the last function call before the stack starts to become less sense to me.

If you are able to disable minification temporarily and see if it works that might provide more insight.

**Comment by andrei572** [comment]
Thanks again, will give it shot.
