### ISSUE TITLE
Is there functionality to 'uncheck' an option once another is selected?

### ISSUE THREAD

**Issue by jinjo30** [nobleclem/jQuery-MultiSelect#131]
I have an option as 'All' for the user. But once they choose something besides 'All' I want it to automatically 'uncheck' the 'All' option. I tried adding my own jquery to work around this but it saves the value of the input from the 'All' option still. Thanks.

**Comment by jinjo30** [comment]
The issue as above accidentally closed issue.

**Comment by nobleclem** [comment]
You should be able to do something like #43 in order to accomplish what you want.  Using that callback and then checking if the current option is selected as well as not being the "All" option.  If that is true then unchecking the "All" option.

**Comment by jinjo30** [comment]
Thank you!

**Comment by jinjo30** [comment]
@nobleclem if you have a moment to type it out could you explain what's going on with this code:

                     $(element).next('.ms-options-wrap')
                            .find('input[value!="' + $(option).val() + '"]:checked')
                            .trigger('click');

1. Is it going through each element with the class '.ms-options-wrap' within the select tag?
2. Not entirely sure what the .find is doing, whats confusing me more so is what's inside of the .find()
3. And I'm assuming it's just triggering a click event with the last part? 

If you don't have the time to explain no worries - or if it's easier just direct me somewhere I can read up on what's going on. Trying to be more efficient with jQuery. Thanks!

**Comment by nobleclem** [comment]
`element` is the `<select>` element, so starting from there its looking for the element `.ms-options-wrap` that is created by this plugin.  From there its looking for a checked input (checkbox) of any other value than the currently checked value.  And correct the last part just triggering a click event.

So in example in issue #43 this is only allowing 1 option to be selected.  For your case maybe something like:
```
if( $.inArray( 'ALL', $(element).val() ) && $(element).val().length > 1 ) {
    $(element).next('.ms-options-wrap')
        .find('input[value!="ALL"]:checked')
        .trigger('click');
}
```

You could also get a little more elegant with the solution so that if someone has 1 or more values selected and they click the "ALL" option that it uncheck the other options and just leaves the "ALL" option selected.

**Comment by jinjo30** [comment]
@nobleclem thank you very much! I was able to get it to function as I was hoping.
