### ISSUE TITLE
v2.4.12 -- select.val() may be null and throw an exception

### ISSUE THREAD

**Issue by aegistics** [nobleclem/jQuery-MultiSelect#133]
initial web page environment -- jQuery jquery.1.11.js and jquery-ui.1.11.js
(this is a legacy web application so don't have the luxury of updating jQuery version at this time)

after jQuery loaded then load jQuery plug-ins in this order
DataTables v1.10.18
jQuery-MultiSelect v2.4.12

jQuery-MultiSelect plug-in version 2.4.12 -- LINE 829 --
variable, "select", may be null and throw an exception

-- FIX -- patched LINES 828-830
else if( (placeholderTxt.width() > placeholder.width()) || (selOpts.length != selectVals.length) ) {
    placeholderTxt.text( select.val().length + instance.options.texts.selectedOptions );
}

else if( (placeholderTxt.width() > placeholder.width()) || (selOpts.length != selectVals.length) ) {
    // select.val() may be null and throw an exception
    if (select.val() !== null ) {
        placeholderTxt.text( select.val().length + instance.options.texts.selectedOptions );
    } else {
        placeholderTxt.text( instance.options.texts.placeholder );
    }
}

**Comment by nobleclem** [comment]
So in all reality that shouldn't happen.  If it's null there then that means that selectVals should be null or 0 as well as selOpts.  Since all of those are linked to the select variable being that of the <select> element.

However it did expose a poor choice for setting the `select` variable by me.  Instead of traversing for it I should have just done `var select = $(instance.element);`.  So I have updated the code to reflect that and a couple other optimization tweaks in `2.4.13`.  If select is null then there has to be something else that is causing the problem.  Does it happen for you on all browsers or just a specific one?

If this truly is a bug then I think I would need to see a standalone example so I can see and work with the problem.  Right now its not something I am able to replicate.

**Comment by aegistics** [comment]
Thanks for your quick response. This issue appeared in all of the browsers I use for testing during development (Chrome 67, Firefox 61, and IE 11). I should note that in my implementation of the jQuery-MultiSelect plug-in v2.4.12 (and now v2.4.13), I do not initially have any options selected in dropdown lists which might explain the original problem where select.val() was null. The updated code in version 2.4.13 fixed that issue. In my implementation I am also generating custom multiselect placeholder text so I was not able to test if your code fix affected the placeholder text configuration option provided. Because the jQuery-MultiSelect and DataTables plug-in code is spread across several templates, I don't have easy access to a standalone example to link to. In the near future I plan to create a simple demo for testing configuration settings when using DataTables and jQuery-MultiSelect and how they may interact. When I do that I will post a link here.
