### ISSUE TITLE
Best way to load huge list of option without slow or laggy page

### ISSUE THREAD

**Issue by Kannanprs84** [nobleclem/jQuery-MultiSelect#146]
I am trying to load a huge list of options approx. 10000 options, and it very slow. It slowing my whole page, slowing other jquery to run, slowing itself when clicked, takes time to open dropdown. 
but the whole page is slow when scrolling, and clicking the dropdown icon. It is respond the click after 30 to 45 seconds. I am using 10 to 11 multiple select controls. The values are 5000,3000, 10000, 4,000 options. If i am opening pane which is having multiselect control it will tak
![dropdownissue](https://user-images.githubusercontent.com/43374971/49635122-c2470100-fa24-11e8-8019-d21bdb213ce4.jpg)
e 20 to 45 second. 

These options are dynamic, they are select dropdown loaded at runtime and i have implemented your jquery-multiselect as follow:

I am using jQuery-MultiSelect Version: 2.4.14  

 
bindMultiDropDown: function (values) {

                $('#InbndAirline').multiselect('reset');
                $('#InbndAirline').multiselect('loadOptions', values);
                $('#InbndAirline').multiselect('refresh');
            } 

values contains in the form 

name: stringvalue
value:integervalue

How to handle this issue. Please provide the solution for this.

**Comment by nobleclem** [comment]
I have done extensive performance improvements to the plugin but unfortunately to keep the functionality that I want in the plugin there is not much more I can do.

There are only a couple of potential solutions I can think of for this case.

1) Instead of loading all of the options you might want to consider going the type ahead route.  Where you search and load a subset of options for a user to select from.  This could be accomplished with this plugin using the `onSearch` callback.  There is a pseudo example in issue #5.

2) Don't use this plugin and build the interface from scratch.  By doing this you can eliminate some functionality you may not need thus speeding up the page load.
