### ISSUE TITLE
Rotating arrow

### ISSUE THREAD

**Issue by zoodov** [nobleclem/jQuery-MultiSelect#148]
Hi)
I offer you to create a simple animation of rotating rightside arrow when toggle option list.
I think it will be great)

**Comment by zoodov** [comment]
I want to add something:
- it will be great if 'search' freeze at top of `div.ms-options` while scrolling option list.
- there is option 'selectAll'. I think option 'UNselectAll' will be useful.

**Comment by zoodov** [comment]
How сan i programmaticaly unselect all options?

**Comment by nobleclem** [comment]
> Hi)
> I offer you to create a simple animation of rotating rightside arrow when toggle option list.
> I think it will be great)

This is something that should be simple for you to customize with some css.  The arrow is right now just a carefully crafted css top-css border.  So you could add css to your project like (this is untested):
```
.ms-options-wrap.ms-active > button:after {
    border-top-color: transparent;
    border-left-color: #999;
    right: 0;
}
```


> I want to add something:
> 
> * it will be great if 'search' freeze at top of `div.ms-options` while scrolling option list.
> * I think option 'UNselectAll' will be more useful if it apears when at least one option the list is selected. Now that jption apears when all options are selected.

These are something I will consider for a future enhancement.  However I want to keep this plugin simple so that users can easily customize to their projects needs.  So some though on how to best implement either of these will have be done.  The (un)select all can be argued both ways.  I might be able to provide an option that allows both to be added.


> How сan i programmaticaly unselect all options?

```
$('select['multiple']').val('').multiselect('reload');
```
