### ISSUE TITLE
Option maxPlaceholderOpts

### ISSUE THREAD

**Issue by pbalbino** [nobleclem/jQuery-MultiSelect#153]
I'm loading the options dynamically through an ajax call. But even though I have a single option selected, the control will show "1 Selected".

    `<div class="form-group">
	@Html.LabelFor(m => m.FkClassificacaoVistoriador, new { @class = "col-sm-3 control-label" })
	<div class="col-sm-9">
		@Html.DropDownList("Teste", Enumerable.Empty<SelectListItem>(), new Dictionary<string, object> { { "class", "form-control input-sm" }, { "multiple", "multiple" } })
	</div>
</div>`

    `$(document).ready(function() {

    var lstOption = [];
    onOpenLoading("vistoriador-update-loading");
    $.ajax({
        url: urlVistoriadorClassificacaoSelectedsGetAsync,
        type: "POST",
        data: { lstIdSelected: $("#VistoriadorClassificacaoId").val() },
        async: false,
        success: function (resultServer) {
            onCloseLoading("vistoriador-update-loading");
            if (resultServer.result) {
                if (resultServer.msg) {
                    onToastWarning(resultServer.msg);
                }
                lstOption = resultServer.options;
            } else {
                if (resultServer.msg) {
                    onToastError(resultServer.msg);
                }
            }
        },
        error: function (xhr, ajaxOptions, thrownError) {
            onCloseLoading("vistoriador-update-loading");
            if (xhr !== null) {
                onToastError("Não foi possível obter a classificação do vistoriador. Erro: " + xhr.responseText);
            } else {
                onToastError("Não foi possível obter a classificação do vistoriador.");
            }
        }
    });

    $("select[multiple]").multiselect({
        texts: {
            placeholder: "Selecione a classificação",
            selectedOptions: " Selecionado(s)",
            selectAll: "Selecionar todos",
            unselectAll: "Remover a seleção de todos"
        },
        selectAll: true,
        maxPlaceholderOpts: 3
    });
    $("select[multiple]").multiselect("loadOptions", lstOption);

    });`

![image](https://user-images.githubusercontent.com/25305220/55253802-0ad53500-5235-11e9-9cee-ca99de4abdc9.png)

But if I uncheck an option and then mark it again the control will display correctly.
![image](https://user-images.githubusercontent.com/25305220/55253890-466fff00-5235-11e9-87ed-1b4a45a6d248.png)

I would like 3 options to be displayed, only after the fourth option could display "4 Selected".

I found the "maxPlaceholderOpts" option to set this, but I do not think so.

**Comment by nobleclem** [comment]
So I tested your options in my environment and wasn't able to reproduce the issue.  However that doesn't mean something else is interfering with the logic for what text is displayed.

The logic starts on Line 783.  So basically what happens is this function is called at the end of loadOptions as well as a few other places in the code.  The logic basically says put all selected items text up to the maxPlaceholderOpts into the <span> within the <button>.  Then it checks if the width of the <span> is greater than the width of the <button> OR if the number of items in the text is not equal to the number of items actually selected.  If either of these cases is true then you get the default "1 selected".

So because I am not seeing a direct issue with the plugin I wonder if there is other styling on the page that is making the width calculation not work as expected.  This could be because styles have not loaded.

To test this try doing something like:

```
$(document).ready(function(){
    $(window).on('load',function(){

        /** PUT YOUR AJAX CODE HERE **/

        $("select[multiple]").multiselect({
            texts: {
                placeholder: "Selecione a classificação",
                selectedOptions: " Selecionado(s)",
                selectAll: "Selecionar todos",
                unselectAll: "Remover a seleção de todos"
            },
            selectAll: true,
            maxPlaceholderOpts: 3
        });
        $("select[multiple]").multiselect("loadOptions", lstOption);
    });
});
```

What that should do is not execute that code until after all declared assets have loaded.  If you are dynamically adding javascript and css then this won't affect it.

**Comment by pbalbino** [comment]
Thank you for the informations. I did the test the way I did, but the control lost the layout.
![image](https://user-images.githubusercontent.com/25305220/55258887-e97b4580-5242-11e9-97de-c5116b4ecc75.png)

One issue I forgot to mention is that this screen is a modal screen.

**Comment by nobleclem** [comment]
So the modal is going to make this difficult for me to debug.  There are a few ways those can be managed and I simply don't have enough in front of me to properly debug it.

This plugins code needs to execute after the HTML has been loaded.  So if you have a modal that you are dynamically loading into the DOM then it needs to be added to the DOM and the modal has to be displayed before the plugin can properly run the calculation of if the text can fit into the <button> element.  If it isn't done in that order then your initial result could likely happen.

Does that make sense?  It's basically an order of operations issue is my current thought for your issue.
