### ISSUE TITLE
Add html tag in option 

### ISSUE THREAD

**Issue by janice0324** [nobleclem/jQuery-MultiSelect#154]
is it possible to add html tag like br/ a  in option

**Comment by nobleclem** [comment]
Since this is just a more user friendly way to interface with a regular <select> list the answer is no.  <option> tags are not permitted to have anything but text in them.  Even if some browsers allow it it is not permitted by the HTML spec.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option
