### ISSUE TITLE
"ms-options" are obscured by the parent div.

### ISSUE THREAD

**Issue by zero12a** [nobleclem/jQuery-MultiSelect#176]
**Describe the bug**

When parent div position of "Div 'ms-options' " is relative. "Div 'ms-options'" hidden and "Parent div" scrolled vertical.

Field name "IMGTYPE4" of attach file "multiselect.js" is not good.

Another field name "IMGTYPE5" of attach file "select2.js" is good.

**To Reproduce**

**Expected behavior**

"Div 'ms-options' " is  top of div.

**Screenshots**

![select2_js](https://user-images.githubusercontent.com/33210572/90312445-79588700-df3f-11ea-9bfa-68accae43ec1.png)
![multiselect_js](https://user-images.githubusercontent.com/33210572/90312447-7a89b400-df3f-11ea-8e2d-0af125ef302e.png)

**Desktop (please complete the following information):**
 - OS: mac 10.15
 - Browser : firefox  79.0 and chrome 
 - Version : multiselect 2.4.18

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nobleclem** [comment]
I don't fully understand the issue you are having.  In both cases it looks like the lists are showing correctly to me.  However this project doesn't have any files by the name of `select2.js`.  So I don't know what that refers to.

**Comment by zero12a** [comment]
**multiselect bug example**
<html>
<head>
    <title>multiselect bug</title>
    <link href="" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@nobleclem/jquery-multiselect@2.4.19/jquery.multiselect.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@nobleclem/jquery-multiselect@2.4.19/jquery.multiselect.css" type="text/css" charset="UTF-8">


    <script>
    
$(document).ready(function() {
    $('#tSelect').multiselect({
        columns: 1,
        maxWidth : 200
    });


    tarr = [
        {value:"cd1",name:"nm1"},
        {value:"cd2",name:"nm2"},
        {value:"cd3",name:"nm3"},
        {value:"cd4",name:"nm4"},
        {value:"cd5",name:"nm5"},
        {value:"cd6",name:"nm6"},
        {value:"cd7",name:"nm7"},
        {value:"cd8",name:"nm8"},
        {value:"cd9",name:"nm9"},
        {value:"cd10",name:"nm10"},
    ];

    $('#tSelect').multiselect( 'loadOptions', tarr);
});

</script>
</head>

<body>
<div style="position:relative;width:400px;height:200px;overflow:auto;background-color:silver;padding-left:30px;">
    <span style="float:left;background-color:yellow;">multiselect.js label : </span>
    <div style="position:absolute;float:left;width:200px;left:170px;"><select id="tSelect" multiple ></select></div>
</div>


</body>
</html>

**Comment by zero12a** [comment]
Dear nobleclem.

Multiselect.js example is this link ( https://github.com/zero12a/ds/blob/master/demo_multiselect_bug.html )
Select2.js example is this link ( https://github.com/zero12a/ds/blob/master/demo_select2_bug.html )

Thank regards.

**Comment by nobleclem** [comment]
So the problem in your example is that the wrapping `div` with the `silver` background has a max-height of 200px.  The entire multiselect is contained within this `div`.  So you would need to set the maxHeight parameter in the plugin to that of the div minus the height of the `<button>` (28px by default).  Now if the `maxHeight` is less than 200px then you would need to set the `minHeight` to this same value as maxHeight cannot be greater than minHeight which has a default value of 200px.

So in your example you would need to do the following:
```
$('#tSelect').multiselect({
    columns: 1,
    maxWidth : 200,
    minHeight: 170,
    maxHeight: 170
});
```


Now the other library `select2.js` that is not maintained by me places its options list at the same level as your `div` with the `max-height: 200px` on it.  So because of that it is not constrained by the height and can overlap it as it does in your example.
