### ISSUE TITLE
it is mot working in modal of bootstrap

### ISSUE THREAD

**Issue by Indianoor** [nobleclem/jQuery-MultiSelect#207]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nobleclem** [comment]
Since you didn't provide any information I can only assume that the issue relates to the dynamic nature of the modal content.  That content was loaded after the multiselect had been initialized.  So you will need to find an appropriate place in your code to initialize the multiselect.  You might be able to trigger the `$('select[multiple]').multiselect( 'reload' );` callback after the modal content had been loaded into the DOM.
