### ISSUE TITLE
Is there an event that fires when the dropdown is closed?

### ISSUE THREAD

**Issue by Lucas-S** [nobleclem/jQuery-MultiSelect#24]
The subject should say it all. I am looking for an event like onOptionClick that is called once the user closes the dropdown (ie: clicks out of the control) so that I can send the whole lot back to the server in one hit.
cheers,
Lucas.

**Comment by triynko** [comment]
Issue #24 actually breaks existing listeners and breaks multi-instance support.  It's calling 'off/on' for the 'click.ms-hideopts' event with no parameters, so it wipes out all the listeners for all but the very last instance constructed.  I had manually attached a 'click.ms-hideopts' listener to the document for all my instances before this was implemented, and after upgrading from V 2.0.1 it stopped working.  This change explains why it stopped working, and from looking at it, it seems that it will also break the listeners for all previously constructed instances.  May want to abstract that handler function into a variable so that when you call 'off', you're also passing the function reference so you're only removing that handler, rather than removing it globally, which affects all instances.
