### ISSUE TITLE
how to use ajax search in multiselect

### ISSUE THREAD

**Issue by tienn2t** [nobleclem/jQuery-MultiSelect#3]
Hello, first to many thanks your helpful plugin.
But i want to use ajax to get data multiselect, can you help me?

**Comment by nobleclem** [comment]
Right now the plugin doesn't support loading select list options through remote calls.  Only option I can think of with how the plugin is written right now is to load the options into a <select> element and then initialize the plugin for that element.

**Comment by tienn2t** [comment]
thanks @nobleclem.

**Comment by nobleclem** [comment]
New overhauled code is now available.  You should be able to use the following items to accomplish what you want.  You will have to write some custom logic to accomplish what you want.

```
$('select[multiple]').multiselect({
    searchOptions: {
        onSearch: function( element ) {
            var newOptions = [
                {
                    name: 'Option Name 1',
                    value: 'option-value-1',
                    checked: false
                },
                {
                    name: 'Option Name 1',
                    value: 'option-value-1',
                    checked: false
                },
            ];
            $(element).multiselect( 'loadOptions', newOptions );
        }
    }
});
```

You will need to also manually set the native select list options so that the plugin will find it and mark them as checked.
