### ISSUE TITLE
Issue Reports

### ISSUE THREAD

**Issue by SoftCircuits** [nobleclem/jQuery-MultiSelect#31]
Sorry to pester you (and thanks for accepting my other code changes), but I'm seeing a couple of other issues.
#### Placeholder Text Grows without Limit

If I click the **Select All** option, all items in the list appear in the placeholder text, and the width of the placeholder container grows way too wide.

Looking at the code, this line doesn't look quite right:

```
// if copy is larger than button width use "# selected"
if( copyWidth > placeWidth ) {
    placeholder.text( selOpts.length + instance.options.texts.selectedOptions );
}
```

Prior to this code, you have just created a copy of the placeholder, and then set the text of the original placeholder to hold all selected items. So how could the `copyWidth` be wider than `placeWidth`?

Perhaps I'm not fully understanding the logic behind this, but would appreciate if you could look at this issue.
#### Reverse Handling for Select All

If I start with a multiselect control with nothing checked, and then click the **Select All** option, all items in the list are correctly checked. But the selected items do not appear in the placeholder text. If I click the **Select All** option a second time, now all items in the list are correctly unchecked. But the selected items now _do_ show up in the placeholder text.

The placeholder text and the checkmarks are now out of sync.

Thank you for any attention you can give these issues.

**Comment by nobleclem** [comment]
**Placeholder Text**
I create a copy in order to apply slightly different css so that it will behave in a way that allows it to grow beyond what the normal placeholder element does.  So you see the part where I add the copy to the DOM then I run through the width calculations and when its all done I remove the element that I added.  If I didn't remove the element it will show that at least in my example and other real world uses of the plugin I would get something that looks like this (showing the copy element in comparison to the normal placeholder).  The pink area is the form element or in my demo the parent of the select menu.
![screen shot 2016-06-06 at 2 20 06 pm](https://cloud.githubusercontent.com/assets/1168820/15832888/3ea5f2e6-2bf2-11e6-9dde-ab58943acff7.png)

**Reverse Handling for Select All**
I suspect that there might be other JS conflicting with this plugin.



If you could provide a sample of either of these not working where I could actually see and interact with the css/js/html then I might be able to help more.  Unfortunately if I can't replicate the issue I often am unable to attempt to fix or provide a reason for why its not working as expected.

**Comment by SoftCircuits** [comment]
Regarding the _reverse handling_ for `Select All`, that turned out to be an issue resulting from us using an old version of jQuery, which we've now updated. Reviewing the sizing issue.

**Comment by GakuseiDev** [comment]
Hi,

As a feedback I can say this feature works well. 
The placeholder updates when a new option is checked, as long as the placeholder text doesn't exceed the available place we can read the checked options values and then the number of selected ones.

**Comment by GakuseiDev** [comment]
Hi,

I encountered the same issue about the placeholder text making the button element growing with no limit but I figured out this can be fix by changing the width of the ".ms-options-wrap" in the css files.
Indeed, for specific needs in my project I added :
```
.ms-options-wrap {
    width : 40%;
    float : right;
}
```
in the css config and now the feature works well. The placeholder text no longer grows too much. As soon as it should exceed the available place it becomes "x selected".
