### ISSUE TITLE
Does this support single selection? 

### ISSUE THREAD

**Issue by patilpranali** [nobleclem/jQuery-MultiSelect#43]
This is a nice plugin however, It would be great if it has the option to decide between single or multi-selection, keeping all other functions as is.

I need to use single selection and multiselction dropdowns on a single form. but if I use this multiselect, and some other single select, then the look and feel is different which is not a big deal to adjust but I wanted other functions like seach on my single select too.

**Comment by nobleclem** [comment]
This plugin was designed to be for multiselect lists because the default interface requiring people to control-click to select multiple items is not a very user friendly method.  Now that being said, this plugin is not meant to have a bunch of features but a base set with the ability to add additional application specific needs as needed.  To do something like what you want you could use the `onOptionClick` callback to uncheck other selected options when a new one is selected.

**Example:**
```
$('select[multiple]').multiselect({
    onOptionClick: function( element, option ) {
        if( $(option).is(':checked') ) {
                $(element).next('.ms-options-wrap')
                    .find('input[value!="'+ $(option).val() +'"]:checked')
                    .trigger('click');
        }
    }
});
```
