### ISSUE TITLE
jQuery Multiselect working with AngularJS ng-Options

### ISSUE THREAD

**Issue by jamminjime** [nobleclem/jQuery-MultiSelect#52]
I have been working with your jQuery.Multiselect control (v2.1.2) for almost a week, trying to get it to work with a <select> that has the options dynamically generated by AngularJS.  

The data is retrieved from a web service call.  In the promise, the data is stored in an array, a filtered list is created and stored into a separate array that the <select> element is bound to, and then initialization of your control is called.  Here is the declaration of the <select> element...

`<select multiple="multiple" name="commodity" id="Commodity" ng-model="selectedCommodity" ng-options="commodity for comm in availableCommodities">`

When the page renders, all of the static options are created successfully, but the dynamic one is not.  If I use the <F12> tools, I can see that the options list is being created and is in the hidden <select> control.  Each of the options contains an ID, a value, and text.  

I have tried moving the control's initialization all over the page and even into the JavaScript file for the page.  I have also attempted to hold the control's initialization until after the AngularJS data has been retrieved and bound to the scope variable to make sure that the <select> element had the <option> elements within it.  I have also tried the jquery.actual plugin but I'm not sure what options to set in your control for the other plugin.

Any help that you could give me would be greatly appreciated!

EDIT: I just updated to 2.3.0 and tried it again.  I get a single check box with no text and no "value" when I click it.

Thanks,
Jim Evans

**Comment by nobleclem** [comment]
So jquery.actual is only really useful if the select list is hidden when you initialize jquery.multiselect.  Because hidden elements do not have a height/width some work cannot be accurately done without jquery.actual that is able to determine the height/width of hidden elements.

So as far as your issue I am not sure.  I have never used AngularJS so all I could give is some guidance rather than real solutions.

There are two ways to get data into the jquery.multiselect interface.

1. Load/Reload jquery.multiselect after the `<select>` list has been rendered/updated.
2. Add data using the `loadOptions` method as demoed in this [issue](https://github.com/nobleclem/jQuery-MultiSelect/issues/26#issuecomment-219332904).
