### ISSUE TITLE
How to implement jquery.actual

### ISSUE THREAD

**Issue by mojtaba** [nobleclem/jQuery-MultiSelect#67]
I want to use the multiselect inside an element which is hidden on page load. I can't figure out how to implement actual plugin to solve the problem.

**Comment by nobleclem** [comment]
Assuming your problem is the only one I have encountered which is that preselected options overflow and doesn't show "# selected" on the button instead.

All you should have to do is load the jquery.actual.js script into the DOM.  The MultiSelect plugin checks for its existence and utilizes it for size calculations.  You don't have to write any javascript in order for the actual plugin to be utilized.  Currently its only used for determining if the selected items overflow the button or not.

**Comment by mojtaba** [comment]
My problem is exactly what you mentioned. But loading jquery.actual.js did not solve my problem.
I am using the multiselect inside a Zurb Foundation accordion list. Can you please have a look at the attached file which contains the error?
[mutliselect accordion.zip](https://github.com/nobleclem/jQuery-MultiSelect/files/705799/mutliselect.accordion.zip)

**Comment by nobleclem** [comment]
So looking at this problem what I think is solving it for me is on the fieldset (parent element of your select list) adding the css
`min-width: inherit;`
makes it cooperate.

one of the things I am seeing on chrome is a user agent stylesheet default for the fieldset element of
`min-width: -webkit-min-content;`

**Comment by mojtaba** [comment]
Thank you very much. Adding `min-with: inherit` to the parent `<fieldset>` element did solve the problem.
