### ISSUE TITLE
Toggle 'select all' to 'deselect all'

### ISSUE THREAD

**Issue by atlanticstarr1** [nobleclem/jQuery-MultiSelect#68]
Thanks for the recent changes to the control. They have been tremendously helpful. Can you change the 'select all' text to 'deselect all' when all options are selected ? Some users have suggested it would be more user friendly that way.

**Comment by nobleclem** [comment]
So that probably is something I could add but its possible that doing so may slow down the plugin for larger datasets like you have.

The way I would implement is I would do a check to see if there are any options NOT selected.  Then based off that check use the select or unselect wording.  Its just another search through the dom that would have to happen.
