### ISSUE TITLE
I want to show close button in the list. how can i do it ?

### ISSUE THREAD

**Issue by mjunaid720** [nobleclem/jQuery-MultiSelect#86]
I want to show close button in the list. how can i do it ?
by default there is no close button with multiselect. how can we add a close button in this list to close the list.

**Comment by nobleclem** [comment]
This is something that I don't think is necessary.  This operates almost like a regular select list.  So because of that a close button is just an extra unnecessary element.

I am sure you could do that but you would need to use one of the existing callbacks like onLoad to add the element to the interface.  Then you can add your custom code to control the closing of the list when the element is clicked.

**Comment by Sachelis** [comment]
I'd vote for a Close button, too. A regular select list closes when you click on an item (unless you Ctrl+click to multi-select). I don't think it's obvious to users that after selecting checkboxes, they need to click outside of the list. I think an "x" in the upper-right corner of the list would be helpful.
